name: Continuous Integration
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.86.0
        with: { components: rustfmt }

      - run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.86.0
        with: { components: clippy }

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check with Clippy
        run: cargo clippy

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.86.0

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: install poppler
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Node Dependencies
        run: yarn install --cwd tests/fixtures/static_server

      - run: cargo test --all-features
